language: node_js
sudo: required
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
    fi
jobs:
  include:
    - name: Lint
      script: yarn lint
    - name: Unit Test
      script: |
        if [ "${TRAVIS_BRANCH}" == "master" ]; then
          yarn run-s test:coverage coveralls
        else
          yarn test:coverage
        fi
    - name: End-to-End Test
      script: yarn run-s build:prod e2e:ci
    - stage: deploy
      name: Deploy
      if: (branch = release-test) AND (commit_message = deploy)
      script: yarn run-s release deploy
addons:
  chrome: stable
