language: node_js
sudo: required
node_js:
  - node
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
addons:
  chrome: stable
jobs:
  include:
    - stage: test
      # Add an IPv6 config - see the corresponding Travis issue
      # https://github.com/travis-ci/travis-ci/issues/8361
      before_script: >-
        [ "${TRAVIS_OS_NAME}" == 'linux' ] &&
        sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
      script: >-
        coveralls="$([ "${TRAVIS_BRANCH}" == 'master' ] && echo 'coveralls' || echo '')" &&
        yarn run-s -c $(echo "lint test:coverage ${coveralls} e2e:ci" | tr -s ' ')
    - stage: deploy
      if: (branch = master) AND (env(RELEASE_BUILD) = true)
      script: >-
        git fetch --unshallow &&
        git checkout "${TRAVIS_BRANCH}" &&
        git remote set-url --push origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" &&
        yarn release:local
