language: node_js
sudo: required
node_js:
  - node
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: test
      # Add an IPv6 config - see the corresponding Travis issue
      # https://github.com/travis-ci/travis-ci/issues/8361
      before_script: >-
          [ "${TRAVIS_OS_NAME}" == 'linux' ] && sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
      script: >-
        yarn run-s -c
        $(echo "lint test:coverage $([ "${TRAVIS_BRANCH}" == 'master' ] && echo 'coveralls' || echo '')" | tr -s ' ')
      if: commit_message != release
      addons:
        chrome: stable
    - stage: deploy
      if: (branch = release-test) AND (commit_message = release)
      script: >-
        chmod +x scripts/deploy.sh
        git checkout ${TRAVIS_BRANCH} &&
        git remote set-url --push origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" &&
        yarn release --git.requireCleanWorkingDir=false
