language: node_js
sudo: required
node_js:
  - node
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - |
    if [ "${TRAVIS_OS_NAME}" == 'linux' ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
    fi
script: >
  yarn run-s -c
  $(echo "lint test:coverage $([ "${TRAVIS_BRANCH}" == 'master' ] && echo 'coveralls' || echo '')" | tr -s ' ')
deploy:
  - provider: script
    script: |
      if [ "${TRAVIS_COMMIT_MESSAGE}" == 'deploy' ]; then
        yarn run-s release deploy
      fi
    on:
      branch: release-test
addons:
  chrome: stable
