language: node_js
sudo: required
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
    fi
jobs:
  include:
    - name: lint
      script: yarn lint
    - name: unit tests
      script: yarn run-s test:coverage coveralls
    - name: e2e tests
      script: yarn run-s build:prod e2e:ci
    - name: deploy
      if: (branch = release-test) AND (env(TRAVIS_COMMIT_MESSAGE) = release) AND (type NOT IN (pull_request, cron))
      script: yarn run-s build:prod release && bash scripts/deploy.sh
addons:
  chrome: stable
