language: node_js
sudo: required
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
    fi
script:
  - yarn run ci
deploy:
  provider: script
  script: yarn release && bash scripts/deploy.sh
  skip_cleanup: true
  if: (env(TRAVIS_COMMIT_MESSAGE) = release) AND (type NOT IN (pull_request, cron))
  on:
    branch: release-test
addons:
  chrome: stable
